### ISSUE TITLE
Curve25519 ECDH doesn't produce test vectors

### ISSUE THREAD

**Issue by mahrud** [indutny/elliptic#142]
I'm working on implementing ed25519/curve25519 for OpenPGP.js. EdDSA using ed25519 works fine with some modifications to this library, however, I haven't been able to get ECDH using curve25519 to work. I found a few issues related to key generation that I'll include in a pull request soon, but there's a bigger problem that the implementation doesn't produce correct test vectors from [RFC7748](https://tools.ietf.org/html/rfc7748#section-5-2):

```
   Input scalar:
     4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d
   Input scalar as a number (base 10):
     35156891815674817266734212754503633747
     128614016119564763269015315466259359304
   Input u-coordinate:
     e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493
   Input u-coordinate as a number (base 10):
     88838573511839298940907593866106493194
     17338800022198945255395922347792736741
   Output u-coordinate:
     95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957
```

Sample code:
```
var curve = require('elliptic').ec('curve25519'),
    BN = require('bn.js'),
    util = require('openpgp').util;

function rev(h) {
  return h.match(/../g).reverse().join('');
}

k = curve.keyFromPrivate(rev('4b66e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba0d'))
k.priv.eq(new BN('4dba18799e16a42cd401eae021641bc1f56a7d959126d25a3c67b4d1d4e96648', 16))
u = util.hex2Uint8Array('40'+rev('e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a493'))
p = curve.keyFromPublic(u)
p.pub.getX().eq(new BN('13a415c749d54cfc3e3cc06f10e7db312cae38059d95b7f4d3116878120f21e5', 16))
util.hexidump(k.derive(p.pub).toArray()) ===
  rev('95cbde9476e8907d7aade45cb4b873f88b595a68799fa152e6f8f7647aac7957')
```

**Comment by mahrud** [comment]
I may have identified the source of the problem, though I'm not sure if this is the only cause:

>    Implementations MUST accept non-canonical values and process them as if they had been reduced modulo the field prime. The non-canonical values are `2^255 - 19` through `2^255 - 1` for X25519 and `2^448 - 2^224 - 1` through `2^448 - 1` for X448.

But since all operations are performed mod P, this the implementation fails to produce those. The original paper also mentions that u-coordinate of public keys range form 0 to `255**32`.

**Comment by Valodim** [comment]
I encountered the same issue recently (see https://github.com/open-keychain/open-keychain/pull/2269), and asked on gnupg-devel about it. This is also what caused an implementation in OpenKeychain to take so long, because the numbers never fit. Opinions on whether this is a bug seem to vary:

https://lists.gnupg.org/pipermail/gnupg-devel/2018-February/033437.html

**Comment by mahrud** [comment]
@Valodim it's not a bug, the RFC's specifying x25519 and OpenPGP are simply inconsistent. See [these comments for reference](https://github.com/openpgpjs/elliptic/pull/1#commitcomment-26675356).

The problem above is different though, and I'm not sure what's the best way to proceed.

**Comment by bscloutier** [comment]
Has anyone confirmed that the Base 10 scalar shown above actually generates the hexadecimal version of it also shown above. Understanding the endianess of value shown in hex I get disagreement in both the MSB and LSB with all in between a match. Could there be typos?

I can input the decimal scalar and see a disagreement in the stored hex. I can then print the corresponding value in decimal and it agrees with my input and the supplied base 10 text.

Oddly this is the case with both test vectors. I would question both the leftmost and rightmost hexadecimal bytes. Right now I question my coding but...

**Comment by bscloutier** [comment]
Obviously enough time has past that this must have been corrected or noted somewhere. I just wasn't aware of the errors. I know that I am way behind in incorporating ECC into my TLS implementation. Here are scalars and u-coordinates as I see them (note little-endian).

K1: a046e36bf0527c9d3b16154b82465edd62144c0ac1fc5a18506a2244ba449a44
    31029842492115040904895560451863089656472772604678260265531221036453811406496

U1: e6db6867583030db3594c1a424b15f7c726624ec26b3353b10a903a6d0ab1c4c
    34426434033919594451155107781188821651316167215306631574996226621102155684838

K2: 4866e9d4d1b4673c5ad22691957d6af5c11b6421e0ea01d42ca4169e7918ba4d
    35156891815674817266734212754503633747128614016119564763269015315466259359304

U2: e5210f12786811d3f4b7959d0538ae2c31dbe7106fc03c3efc4cd549c715a413
    8883857351183929894090759386610649319417338800022198945255395922347792736741

You will note that just the scalars are incorrect and then only in the LSB and MSB bytes. The u-coordinates are correct in the document. The same code processes each set.

It would be nice if [RFC7748](https://tools.ietf.org/html/rfc7748) were accurate. I am now off to run the curves and check the results. Just don't know if I can trust what is published. I bet many have lost time because of this.

**Comment by bscloutier** [comment]
Okay. So I now see that you need to set and clear bits in the first and last bytes when handling a randomly generated scalar. So you would think that somehow you would make it obvious in the RFC  that for these test vectors the given scalar in hex only generates the decimal result after bits are adjusted. Geez...
