### ISSUE TITLE
Minerva ECDSA/EdDSA vulnerabilities

### ISSUE THREAD

**Issue by smarek** [indutny/elliptic#202]
Info page: https://minerva.crocs.fi.muni.cz/

Is elliptic really affected, and if so, has there be any development related to mitigating said attacks?

**Comment by J08nY** [comment]
Hi @smarek, all,
we listed elliptic as vulnerable after we performed source code analysis. We did not verify this experimentally.

Looking at the codepaths again it is because the various scalar multiplication functions perform loops that depend on the scalar bit-length in some way (See https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/short.js#L422 for which algorithms are used on Short-Weierstrass curves for ECDSA and https://github.com/indutny/elliptic/blob/master/lib/elliptic/curve/edwards.js#L359 for algos used on Edwards curves for EdDSA).

In the wNAF method, the dependency might be the number of width-w windows, which obviously depends on the bit-length of the scalar.

To be perfectly sure the vulnerability is there, one can perform tests with varying scalar bit-lengths using the different scalar-multiplication for different curves and observe the results.

On the mitigation side, one mitigation was introduced in https://eprint.iacr.org/2011/232 where one basically fixes the bit-length of the scalar to a constant value by conditionally adding a multiple of the curve order to it. Another mitigation is to use an algorithm that has fixed runtime w.r.t. the bit-length of the scalar, usually looping on the bit-length of the order of the curve and using complete addition formulas.

**Comment by J08nY** [comment]
I created a pull request #203 which should mitigate this.

**Comment by alcuadrado** [comment]
Is this fixed in 6.5.1?

**Comment by indutny** [comment]
Hey, I've went ahead and applied alternative "fix": ec735ed . However, as bad as it sounds it must be said that this library was never meant to be timing-leak free. Architecture of elliptic and bn.js was designed to provide the fastest possible pure JS implementation of elliptic curve so that it would be usable in browsers. Patching this one particular loophole doesn't mean that there are no other side-channels (in fact, there are many through the source code).
