### ISSUE TITLE
Threshold cryptography

### ISSUE THREAD

**Issue by lukeburns** [indutny/elliptic#46]
Is it possible to use this library for [threshold cryptography](https://en.wikipedia.org/wiki/Threshold_cryptosystem)? For example, by combining public keys as in this post: http://crypto.stackexchange.com/questions/25250/adding-two-public-keys?

If so, can you give an example on how to combine two public keys into a public key that requires both  private keys to produce a signature?

**Comment by indutny** [comment]
I'm quite sure it should be possible to do it. Though, you may need to use raw secp256k1 primitives instead of the `ECDSA` class.

The example might be a bit complicated: http://www.cs.princeton.edu/~stevenag/bitcoin_threshold_signatures.pdf . I'd go with reading this paper and trying to figure out what kind of primitives you need, and how to use them.
